# Generated by Django 6.1 on 2026-09-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_source',
            field=models.CharField(default='local', max_length=20),
        ),
    ]
