# Generated by Django 6.1 on 2026-08-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_review_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='category',
            new_name='product',
        ),
    ]
